<?php

class Zend_View_Helper_Country extends Zend_View_Helper_Abstract
{

    public function country($params)
    {

        $countries = [
            'Германия' => 'Germany.png',
            'Німеччина' => 'Germany.png',
            'Germany' => 'Germany.png',
            'германия' => 'Germany.png',
            'німеччина' => 'Germany.png',
            'germany' => 'Germany.png',
            'Италия' => 'Italy.png',
            'Італія' => 'Italy.png',
            'Italy' => 'Italy.png',
            'italia' => 'Italy.png',
            'Italia' => 'Italy.png',
            'италия' => 'Italy.png',
            'італія' => 'Italy.png',
            'italy' => 'Italy.png',
            'Словения' => 'Slovenia.png',
            'Словенія' => 'Slovenia.png',
            'Slovenia' => 'Slovenia.png',
            'словения' => 'Slovenia.png',
            'словенія' => 'Slovenia.png',
            'slovenia' => 'Slovenia.png',
            'Словакия' => 'Slovakia.png',
            'словакия' => 'Slovakia.png',
            'Словаччина' => 'Slovakia.png',
            'словаччина' => 'Slovakia.png',
            'slovakia' => 'Slovakia.png',
            'Slovakia' => 'Slovakia.png',
            'Украина' => 'Ukraine.png',
            'Україна' => 'Ukraine.png',
            'Ukraine' => 'Ukraine.png',
            'украина' => 'Ukraine.png',
            'україна' => 'Ukraine.png',
            'ukraine' => 'Ukraine.png',
            'Франция' => 'France.png',
            'Франція' => 'France.png',
            'France' => 'France.png',
            'франция' => 'France.png',
            'франція' => 'France.png',
            'france' => 'France.png',
            'Польша' => 'Poland.png',
            'Польща' => 'Poland.png',
            'Poland' => 'Poland.png',
            'польша' => 'Poland.png',
            'польща' => 'Poland.png',
            'poland' => 'Poland.png',
            'Сербия' => 'Serbia.png',
            'Сербія' => 'Serbia.png',
            'Serbia' => 'Serbia.png',
            'сербия' => 'Serbia.png',
            'сербія' => 'Serbia.png',
            'serbia' => 'Serbia.png',
            'Турция' => 'Turkey.png',
            'Турція' => 'Turkey.png',
            'Turkey' => 'Turkey.png',
            'турция' => 'Turkey.png',
            'турція' => 'Turkey.png',
            'turkey' => 'Turkey.png',
            'Литва' => 'Lithuania.png',
            'Lithuania' => 'Lithuania.png',
            'литва' => 'Lithuania.png',
            'lithuania' => 'Lithuania.png',
            'Таиланд' => 'Thailand.png',
            'Таїланд' => 'Thailand.png',
            'Thailand' => 'Thailand.png',
            'таиланд' => 'Thailand.png',
            'таїланд' => 'Thailand.png',
            'thailand' => 'Thailand.png',
            'Венгрия' => 'Hungary.png',
            'Угорщина' => 'Hungary.png',
            'Hungary' => 'Hungary.png',
            'венгрия' => 'Hungary.png',
            'угорщина' => 'Hungary.png',
            'hungary' => 'Hungary.png',
            'Румыния' => 'Romania.png',
            'Румунія' => 'Romania.png',
            'Romania' => 'Romania.png',
            'румыния' => 'Romania.png',
            'румунія' => 'Romania.png',
            'romania' => 'Romania.png',
            '' => '.png',
            '' => '.png',
            '' => '.png',
            '' => '.png',
            '' => '.png',
            '' => '.png',
            '' => '.png',
            '' => '.png',
            '' => '.png',
            '' => '.png',
            '' => '.png',
        ];






    }
}
