{if $seo_description}{$seo_description}{elseif $description && $description !=''}{$description}
{elseif $zf.params.controller=='catalog'}
{if $zf.params.action=='search'} Поиск {$zf.params.searchtext} в интернет-магазине 590{/if}
{if $zf.params.action=='item'}Купить с доставкой {$item.category_onename|mblower} {$item.brand} {$item.name} в интернет-магазине бытовой техники №❶ 590.ua. ☎(050) 590-0-590. Бесплатная доставка по Киеву и всей Украине.{/if}
{if $zf.params.action=='cat'}{if $seo_h1}{$seo_h1}{else}Купить {php} echo mb_strtolower($this->menu->findOneBy('active', true),'utf-8'); {/php}{if $zf.params.brand}{php}foreach (explode('_',$this->_tpl_vars['zf']['params']['brand']) as $brandId) $brands[] = $brandId; echo mb_convert_case(' '.join(', ', $brands),MB_CASE_TITLE, "UTF-8");{/php}{/if}{if $accepted_filters} ({foreach from=$accepted_filters item=filter name=filters}{$filter.name} - {foreach from=$filter.values item=filterValue name=filter_values}{$filterValue}{if !$smarty.foreach.filter_values.last}, {/if}{/foreach}{if !$smarty.foreach.filters.last}; {/if}{/foreach}) {/if}{if $zf.params.page} - Страница {$pages->current}{/if}{/if} в интернет-магазине бытовой техники №❶ 590.ua. ☎(050) 590-0-590. {if $seo_h1}{$seo_h1|mblower}{else}{php} echo $this->menu->findOneBy('active', true);{/php}{if $zf.params.brand}{php}foreach (explode('_',$this->_tpl_vars['zf']['params']['brand']) as $brandId) $brands[] = $brandId; echo ' '.join(', ', $brands);{/php}{/if}{if $accepted_filters} ({foreach from=$accepted_filters item=filter name=filters}{$filter.name} - {foreach from=$filter.values item=filterValue name=filter_values}{$filterValue}{if !$smarty.foreach.filter_values.last}, {/if}{/foreach}{if !$smarty.foreach.filters.last}; {/if}{/foreach}) {/if}{if $zf.params.page} - Страница {$pages->current}{/if}{/if}: бесплатная доставка по Киеву и всей стране.{/if}
{if $accepted_filters}
Лучшие цены на {if $catId != 1}{php} echo mb_strtolower($this->menu->findOneBy( 'active', true),'utf-8');{/php}{else}бытовую технику{/if} {foreach from=$accepted_filters item=filter name=filters}{$filter.name} - {foreach from=$filter.values item=filterValue name=filter_values}{$filterValue}{if !$smarty.foreach.filter_values.last}, {/if}{/foreach}{if !$smarty.foreach.filters.last}; {/if}{/foreach} в интернет магазине 590.ua. Качественные {if $catId != 1}{php} echo mb_strtolower($this->menu->findOneBy( 'active', true),'utf-8');{/php}{else}бытовую технику{/if} {foreach from=$accepted_filters item=filter name=filters}{$filter.name} - {foreach from=$filter.values item=filterValue name=filter_values}{$filterValue}{if !$smarty.foreach.filter_values.last}, {/if}{/foreach}{if !$smarty.foreach.filters.last}; {/if}{/foreach} по доступным ценам. Мы осуществляем доставку товара {if $catId != 1}{php} echo mb_strtolower($this->menu->findOneBy( 'active', true),'utf-8');{/php}{else}бытовую технику{/if} {foreach from=$accepted_filters item=filter name=filters}{foreach from=$filter.values item=filterValue name=filter_values}{$filterValue}{if !$smarty.foreach.filter_values.last}, {/if}{/foreach}{if !$smarty.foreach.filters.last}; {/if}{/foreach} по всей Украине.
{/if}
{if $zf.params.controller=='catalog' && $zf.params.action=='brand'}Техника {$brandName} в интернет-магазине бытовой техники №❶ 590.ua. ☎(050) 590-0-590. Бесплатная доставка по Киеву и всей стране{/if}
{elseif $zf.params.controller=='page'}{if $page} Интернет-магазин 590, {$pagename|translate|mblower}. Продажа бытовой техники в Киеве, Одессе и Харькове. Доставка, гарантия на все товары. Фото, описание, отзывы, характеристики товаров.{/if}
{elseif $zf.params.controller=='news' && $zf.params.action=='index'}
Новости{if $singleNews}: {$news.name}{/if}. Продажа бытовой техники в Киеве, Одессе и Харькове: холодильники, варочные поверхности, духовки, вытяжки, посудомоечные машины и др.
{elseif $zf.params.controller=='articles' && $zf.params.action=='index'}
Статьи{if $article.announce}: {$article.announce}{/if}. Продажа бытовой техники в Киеве, Одессе и Харькове: холодильники, варочные поверхности, духовки, вытяжки, посудомоечные машины и др.
{else}Большой выбор бытовой техники и электроники в интернет-магазине 590.ua: продажа мелкой, крупной, встраиваемой, климатической техники. Лучшие цены! Гарантия, отзывы, фото. Не знаете, где купить? Звоните (050) 419-38-10.{/if}

