{if !$zf.params.page}
{if $seo_description}{$seo_description}{elseif $description && $description !=''}{$description}
{elseif $zf.params.controller=='catalog'}
{if $zf.params.action=='search'} Поиск {$zf.params.searchtext} в интернет-магазине 590{/if}
{if $zf.params.action=='item'}Лучшая цена на {$item.category_onename} {$item.brand} {$item.name} в интернет магазине 590.ua. Качественные {$item.category_onename} {$item.brand} {$item.name} по доступным ценам. Мы осуществляем доставку {$item.category_onename} {$item.brand} {$item.name} по всей Украине.{/if}
{if $zf.params.action=='cat'}{if $seo_h1}{$seo_h1}{else}{php} echo $this->menu->findOneBy('active', true); {/php}{if $zf.params.brand}{php}foreach (explode('_',$this->_tpl_vars['zf']['params']['brand']) as $brandId) $brands[] = $brandId; echo ' '.join(', ', $brands);{/php}{/if}{if $accepted_filters} ({foreach from=$accepted_filters item=filter name=filters}{$filter.name} - {foreach from=$filter.values item=filterValue name=filter_values}{$filterValue}{if !$smarty.foreach.filter_values.last}, {/if}{/foreach}{if !$smarty.foreach.filters.last}; {/if}{/foreach}) {/if}{if $zf.params.page} - Страница {$pages->current}{/if}{/if} - купить {if $seo_h1}{$seo_h1|mblower}{else}{php} echo mb_strtolower($this->menu->findOneBy('active', true),'utf-8'); {/php}{if $zf.params.brand}{php}foreach (explode('_',$this->_tpl_vars['zf']['params']['brand']) as $brandId) $brands[] = $brandId; echo ' '.join(', ', $brands);{/php}{/if} {if $accepted_filters} ({foreach from=$accepted_filters item=filter name=filters}{$filter.name} - {foreach from=$filter.values item=filterValue name=filter_values}{$filterValue}{if !$smarty.foreach.filter_values.last}, {/if}{/foreach}{if !$smarty.foreach.filters.last}; {/if}{/foreach}) {/if}{if $zf.params.page} - Страница {$pages->current}{/if}{/if}по низкой цене в Украине. Широкий выбор товара на любой вкус. Мы осуществляем доставку товара по всей Украине.{/if}
{if $accepted_filters}
Лучшие цены на {if $catId != 1}{php} echo mb_strtolower($this->menu->findOneBy( 'active', true),'utf-8');{/php}{else}бытовую технику{/if} {foreach from=$accepted_filters item=filter name=filters}{$filter.name} - {foreach from=$filter.values item=filterValue name=filter_values}{$filterValue}{if !$smarty.foreach.filter_values.last}, {/if}{/foreach}{if !$smarty.foreach.filters.last}; {/if}{/foreach} в интернет магазине 590.ua. Качественные {if $catId != 1}{php} echo mb_strtolower($this->menu->findOneBy( 'active', true),'utf-8');{/php}{else}бытовую технику{/if} {foreach from=$accepted_filters item=filter name=filters}{$filter.name} - {foreach from=$filter.values item=filterValue name=filter_values}{$filterValue}{if !$smarty.foreach.filter_values.last}, {/if}{/foreach}{if !$smarty.foreach.filters.last}; {/if}{/foreach} по доступным ценам. Мы осуществляем доставку товара {if $catId != 1}{php} echo mb_strtolower($this->menu->findOneBy( 'active', true),'utf-8');{/php}{else}бытовую технику{/if} {foreach from=$accepted_filters item=filter name=filters}{foreach from=$filter.values item=filterValue name=filter_values}{$filterValue}{if !$smarty.foreach.filter_values.last}, {/if}{/foreach}{if !$smarty.foreach.filters.last}; {/if}{/foreach} по всей Украине.
{/if}
{if $zf.params.action=='brand'}{if !$zf.params.page}Лучшие цены на {$brandName} в интернет магазине 590.ua. Качественные товары {$brandName} по доступным ценам. Мы осуществляем доставку товара {$brandName} по всей Украине.{/if}{/if}
{elseif $zf.params.controller=='page'}{if $page} Интернет-магазин 590, {$pagename|translate|mblower}. Продажа бытовой техники в Киеве, Одессе и Харькове. Доставка, гарантия на все товары. Фото, описание, отзывы, характеристики товаров.{/if}
{elseif $zf.params.controller=='news' && $zf.params.action=='index'}
Новости{if $singleNews}: {$news.name}{/if}. Продажа бытовой техники в Киеве, Одессе и Харькове: холодильники, варочные поверхности, духовки, вытяжки, посудомоечные машины и др.
{elseif $zf.params.controller=='articles' && $zf.params.action=='index'}
Статьи{if $article.announce}: {$article.announce}{/if}. Продажа бытовой техники в Киеве, Одессе и Харькове: холодильники, варочные поверхности, духовки, вытяжки, посудомоечные машины и др.
{else}Большой выбор бытовой техники и электроники в интернет-магазине 590.UA: продажа мелкой, крупной, встраиваемой, климатической техники. Лучшие цены! Гарантия, отзывы, фото. Не знаете, где купить? Звоните (050) 419-38-10.{/if}
{/if}
